name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -o bin/app

    - name: Test
      run: go test -v ./...
      
    - name: Setup binary
      run: |
        [[ -d $HOME/cepex-server/ ]] && mkdir $HOME/cepex-server
        cp ./bin/app $HOME/cepex-server/
    
    - name: Setup unit file
      run: |
          if systemctl --user list-units | grep -q "cepex"; then
            [[ ! -d $HOME/.config/systemd/user/ ]] && mkdir -p $HOME/.config/systemd/user/
            cp ./.systemd/cepex.service $HOME/.config/systemd/user/cepex.service
          else
            [[ ! -d $HOME/.config/systemd/user/cepex.service.d/ ]] && mkdir -p $HOME/.config/systemd/user/cepex.service.d/
            cp ./.systemd/cepex.service $HOME/.config/systemd/user/cepex.service.d/override.conf
          fi
    - name: Run service
      run: systemctl --user enable cepex.service --now
