name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout src
        uses: actions/checkout@v2
      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
      - name: Test
        run: go test -v ./...
      - name: Build go app 
        run: go build -o bin/app 
      - name: Check binary existance
        run: | 
          ls bin/
          pwd
      - name: Set up docker build 
        uses: docker/setup-buildx-action@v1
      - name: Login to docker hub
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: fattfatt/cepex-server:latest

  deploy:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Pull image and run docker via ssh
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd ~/cepex-server
            git pull origin master
            cat << EOF > .env 
            PORT=${{ secrets.PORT }}
            SERVICE_NAME=${{ secrets.SERVICE_NAME }}
            CAPACITY=${{ secrets.CAPACITY }}
            S3_ACCESS_KEY=${{ secrets.S3_ACCESS_KEY }}
            S3_BUCKET=${{ secrets.S3_BUCKET }}
            S3_ENDPOINT=${{ secrets.S3_ENDPOINT }}
            S3_SECRET_KEY=${{ secrets.S3_SECRET_KEY }}
            EOF
            docker-compose pull
            docker-compose down
            docker-compose up -d

    # needs: [ build ]
    # runs-on: self-hosted
    # steps:
    # - uses: actions/checkout@v2
    #   with:
    #     token: ${{ secrets.GH_TOKEN }}

    # - name: Set up Go
    #   uses: actions/setup-go@v2
    #   with:
    #     go-version: 1.15

    # - name: Build
    #   run: go build -o bin/app

    # - name: Test
    #   run: go test -v ./...
    # - name: Run service
    #   env:
    #     PORT: ${{ secrets.PORT }}
    #     SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
    #     CAPACITY: ${{ secrets.CAPACITY }}
    #     S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
    #     S3_BUCKET: ${{ secrets.S3_BUCKET }}
    #     S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
    #     S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
    #   run: /home/fatt/.nvm/versions/node/v16.2.0/bin/pm2 restart bin/app --update-env
