name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GH_TOKEN }}

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -o bin/app

    - name: Test
      run: go test -v ./...
    - name: Run service
      env:
        PORT: ${{ secrets.PORT }}
        SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
        CAPACITY: ${{ secrets.CAPACITY }}
        S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
        S3_BUCKET: ${{ secrets.S3_BUCKET }}
        S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
        S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
      run: /home/fatt/.nvm/versions/node/v16.2.0/bin/pm2 restart bin/app --update-env
